title: QFormats
description: libraries to load various quake related formats written in C++
theme: just-the-docs

url: https://qformats.github.io

search_enabled: false
color_scheme: "qflight"

aux_links:
  QFormats on github <3:
    - https://github.com/qformats
